/**
 * src/metrics/wsBackpressure.ts
 *
 * Per-client WebSocket backpressure gauges and micro-batching counters
 * exposed to Prometheus.
 *
 * ### Backpressure gauges (three series)
 *
 *   - `fluxora_ws_backpressure_buffered_bytes{connection_id="…"}` — current
 *     `ws.bufferedAmount` per client, useful for finding a specific slow
 *     peer.  This is the primary, bounded-cardinality gauge required by the
 *     per-client observability feature.
 *   - `fluxora_ws_max_buffered_bytes`     — max bufferedAmount across all
 *     live clients (low cardinality, suitable for dashboards/alerts).
 *   - `fluxora_ws_slow_clients`           — count of clients whose buffered
 *     bytes exceed the configurable warning threshold (default 1 MiB).
 *
 * ### Micro-batching counters (three series)
 *
 *   - `fluxora_ws_batch_flush_total`         — total flush operations (each
 *     flush produces one outbound `stream_update_batch` frame per client).
 *   - `fluxora_ws_batch_events_coalesced_total` — total individual events
 *     that were coalesced across all flushes.  Comparing this to
 *     `fluxora_ws_batch_flush_total` gives the average batch size.
 *   - `fluxora_ws_batch_size_exceeded_total` — flushes where the batch hit
 *     `WS_BATCH_MAX_SIZE` before the flush window expired (early ejection).
 *
 * The per-client gauge is updated by a poll loop so the value reflects the
 * actual kernel/OS send-buffer state, not just the snapshot taken during a
 * `deliverBatch` call.  Series for disconnected clients are explicitly removed
 * via `removeWsClientBackpressureGauge` to prevent unbounded label
 * accumulation.  See `docs/observability.md` for the labeling-choice rationale
 * and bounded-cardinality guarantee.
 */

import { Counter, Gauge } from 'prom-client';
import { registry } from '../metrics.js';
import type { StreamHub } from '../ws/hub.js';

/**
 * Default warning threshold for "slow client" classification.
 * Mirrors `BACKPRESSURE_DROP_BYTES` in `src/ws/hub.ts` (1 MiB) by default,
 * but can be overridden via `startWsBackpressureCollector` to e.g. trigger
 * before the hub actively drops frames.
 */
export const DEFAULT_WS_SLOW_CLIENT_BYTES = 1 * 1024 * 1024;

/**
 * Default poll interval for the backpressure collector. Five seconds is a
 * reasonable balance between metric freshness and CPU churn when there are
 * many concurrent connections — Prometheus typically scrapes every 15s, so
 * 5s-poll values are always at most one poll-stale in the worst case.
 */
export const DEFAULT_WS_BACKPRESSURE_INTERVAL_MS = 5_000;

// ── Backpressure gauges ────────────────────────────────────────────────────────

/**
 * Per-client backpressure gauge. Labels are intentionally limited to
 * `connection_id` — a UUID v4 generated by the server, low cardinality and
 * free of PII.
 *
 * Cardinality guarantee: at most one time-series per *currently connected*
 * client. Series are removed when the client disconnects
 * (`removeWsClientBackpressureGauge`) to prevent unbounded memory growth
 * in long-running processes.  The label set is therefore bounded by the
 * peak concurrent-connection count, not by total connections over time.
 *
 * @security The `connection_id` label is a server-generated UUID v4. It
 *   never contains client IP, account subject, JWT `sub`, request ID, or
 *   any other identifier that could be used to fingerprint or correlate a
 *   particular user.  The bounded-cardinality design prevents an attacker
 *   from inflating Prometheus memory by repeatedly reconnecting — each
 *   reconnect simply replaces the prior series for that one seat.
 */
export const wsClientBufferedBytes =
  (registry.getSingleMetric('fluxora_ws_backpressure_buffered_bytes') as Gauge<'connection_id'>) ||
  new Gauge<'connection_id'>({
    name: 'fluxora_ws_backpressure_buffered_bytes',
    help: 'Current ws.bufferedAmount per connected WebSocket client on /ws/streams. Bounded by connection_id (server-generated UUID v4); series removed on disconnect.',
    labelNames: ['connection_id'] as const,
    registers: [registry],
  });

/** Maximum bufferedAmount observed across all live WebSocket clients. */
export const wsMaxBufferedBytes =
  (registry.getSingleMetric('fluxora_ws_max_buffered_bytes') as Gauge) ||
  new Gauge({
    name: 'fluxora_ws_max_buffered_bytes',
    help: 'Maximum ws.bufferedAmount observed across all live WebSocket clients',
    registers: [registry],
  });

/**
 * Number of clients whose bufferedAmount exceeds the warning threshold.
 * Useful for SLO alerts: "more than N slow clients" without scanning the
 * per-client series.
 */
export const wsSlowClients =
  (registry.getSingleMetric('fluxora_ws_slow_clients') as Gauge) ||
  new Gauge({
    name: 'fluxora_ws_slow_clients',
    help: 'Number of WebSocket clients whose buffered amount exceeds the slow-client threshold',
    registers: [registry],
  });

// ── Micro-batching counters ────────────────────────────────────────────────────

/**
 * Total number of micro-batch flush operations completed.
 *
 * Each flush emits a single `stream_update_batch` frame to a subscribed client
 * that has opted in via `batching: true` on their subscription.  Monotonically
 * increasing; reset to 0 only by process restart.
 *
 * Use `rate(fluxora_ws_batch_flush_total[1m])` to estimate flush throughput.
 * Divide `fluxora_ws_batch_events_coalesced_total` by this counter to get the
 * rolling average batch size.
 */
export const wsBatchFlushTotal =
  (registry.getSingleMetric('fluxora_ws_batch_flush_total') as Counter) ||
  new Counter({
    name: 'fluxora_ws_batch_flush_total',
    help: 'Total number of micro-batch flush operations that emitted a stream_update_batch frame',
    registers: [registry],
  });

/**
 * Total number of individual events coalesced across all batch flushes.
 *
 * An "event" is counted once per (streamId, eventId) before it enters a
 * batch accumulator.  Deduplication at the broadcast level prevents double-
 * counting when the same event is broadcast twice.
 *
 * `fluxora_ws_batch_events_coalesced_total / fluxora_ws_batch_flush_total`
 * gives the average batch fill ratio over any Prometheus range window.
 */
export const wsBatchEventsCoalescedTotal =
  (registry.getSingleMetric('fluxora_ws_batch_events_coalesced_total') as Counter) ||
  new Counter({
    name: 'fluxora_ws_batch_events_coalesced_total',
    help: 'Total number of individual events coalesced into micro-batch frames',
    registers: [registry],
  });

/**
 * Number of times an early flush was triggered by hitting `WS_BATCH_MAX_SIZE`
 * before the flush window (`WS_BATCH_FLUSH_MS`) expired.
 *
 * Frequent early ejections suggest the max-size limit is too low for the
 * current event throughput.  Consider increasing `WS_BATCH_MAX_SIZE` or
 * decreasing `WS_BATCH_FLUSH_MS`.
 */
export const wsBatchSizeExceededTotal =
  (registry.getSingleMetric('fluxora_ws_batch_size_exceeded_total') as Counter) ||
  new Counter({
    name: 'fluxora_ws_batch_size_exceeded_total',
    help: 'Total number of micro-batch flushes triggered early by hitting WS_BATCH_MAX_SIZE',
    registers: [registry],
  });

// ── Collection helpers ─────────────────────────────────────────────────────────

/**
 * Poll the hub for current `ws.bufferedAmount` values and update all three
 * backpressure gauges.  Safe to call concurrently — prom-client label writes
 * are atomic within a single call, and we only read `ws.bufferedAmount` which
 * is itself node:net state.
 *
 * The function is exported separately from `startWsBackpressureCollector` so
 * tests can drive it deterministically without dealing with `setInterval`
 * timing.
 */
export function collectWsBackpressureMetrics(
  hub: StreamHub,
  slowThresholdBytes: number = DEFAULT_WS_SLOW_CLIENT_BYTES,
): void {
  let maxBuffered = 0;
  let slowCount = 0;

  for (const [ws, state] of hub._getClients()) {
    if (ws.readyState !== ws.OPEN) continue;

    const buffered = safeBufferedAmount(ws);
    wsClientBufferedBytes.set({ connection_id: state.id }, buffered);

    if (buffered > maxBuffered) maxBuffered = buffered;
    if (buffered > slowThresholdBytes) slowCount++;
  }

  // Aggregates are already 0 when no live clients were iterated, so a single
  // assignment is enough to keep dashboards honest when clients churn.
  wsMaxBufferedBytes.set(maxBuffered);
  wsSlowClients.set(slowCount);
}

/**
 * Remove the per-client gauge time series for a disconnected client.
 *
 * Must be called from `StreamHub.onDisconnect` for every client so the
 * label set doesn't grow unbounded across long-lived processes.
 *
 * `prom-client@15` `Gauge.remove(...)` is a no-op when no series exists for
 * the given label combination, so it's safe to call defensively.  Total
 * `remove` calls scale linearly with `disconnect` rate, never with the
 * total number of historical connections — so the in-memory cost is
 * bounded by the current concurrency, not process uptime.
 */
export function removeWsClientBackpressureGauge(connectionId: string): void {
  wsClientBufferedBytes.remove({ connection_id: connectionId });
}

/**
 * Reset all WS backpressure gauges to 0/empty.  Useful between test runs.
 */
export function resetWsBackpressureMetrics(): void {
  wsClientBufferedBytes.reset();
  wsMaxBufferedBytes.set(0);
  wsSlowClients.set(0);
}

// ── Internal helpers ───────────────────────────────────────────────────────────

/**
 * Read `ws.bufferedAmount` defensively.
 *
 * The `ws` library types `bufferedAmount: number`, but in practice the
 * property may be momentarily undefined while a socket transitions state,
 * and tests routinely override it via `Object.defineProperty`.  Returning 0
 * in those edge cases keeps the collector crash-free; the `>= 0` clause also
 * masks the unlikely case of a negative value reported by a buggy library.
 */
function safeBufferedAmount(ws: { bufferedAmount?: unknown }): number {
  const value = ws.bufferedAmount;
  return typeof value === 'number' && Number.isFinite(value) && value >= 0 ? value : 0;
}
